package org.veteroch4k.laba1.Lexicon;

public enum TokenType {
  VARIABLE, NUMBER, STRING,
  L_PAREN, R_PAREN, COLON, COMMA, ASSIGN,
  WHITESPACE, ERROR, EOF, FLOAT,
  IDENTIFIER, KW_FUNCTION,
  TYPE_INT, TYPE_STRING, TYPE_FLOAT,
  QUESTION, SEMICOLON

}
