package org.veteroch4k.laba1;

public enum TokenType {
  FUNCTION, VARIABLE, NUMBER, STRING,
  L_PAREN, R_PAREN, COLON, COMMA, ASSIGN,
  WHITESPACE, ERROR, EOF, FLOAT,
  IDENTIFIER, KW_FUNCTION,
  TYPE_INT, TYPE_STRING,
  QUESTION, SEMICOLON

}
